Natalia bakakuri
bitcamp-ge/bitcamp-resume-review pull request #16
Opened 2020-09-08 07:34 UTC by theonomiMC

2020-09-24 17:06 UTC, otarza requested changes
@theonomiMC ნატალია გამარჯობა, 

შენი რეზიუმე კარგია, ვიზუალურადაც გამართულია, ყოჩაღ!

ერთადერთი შენიშვნა მექნება, რადგან შენი გამოცდილებ ფინანსებშია და შესაბამისად არარელევანტურია ჩვენი პროფესიისთვის, მგონი აჯობებს სულ ბოლოში, ენებამდე ჩაიტანო ეგ სექცია, ან თუ ძაან არ გენანება, შეგიძლია წაშალო კიდევაც, სხვა მხრივ მშვენიერია და რომ გაასწორებ მომწერე აქვე, დამატებით დეტალებს გაგაცნობ.

2021-02-15 23:24 UTC, TGociridze commented
@theonomiMC გამარჯობა. მინდა შენი რეზიუმე სარეკომენდაცო სიაში დავამატო, თებერვლის თვის დასაქმების რაუნდის ფარგლებში. თუ გსურს, რომ Bitcamp ზეც ისაუბრო, შეგიძლია განათლების სექციაში დაწერო Bitcamp, სწავლის პერიოდი და გავლილი ეტაპების რაოდენობა. თუ არადა, შემოტაყობინე, ისე დავამატებ.

2021-02-16 06:35 UTC, theonomiMC commented
@TGociridze გამარჯობა, დავარედაქტირე ბითქემფით რეზიუმე და შეგიძლია დაამატო.

მადლობა ))

2021-02-16 19:54 UTC, TGociridze commented
@theonomiMC საღამომშვიდობის, რეზიუმეს გადავხედე და რამდენიმე რჩევა მსურს გაგიზიარო. ჯობს ინფორმაცია ერთ გვერდზე იყოს გადმოცემული.  bitcamp ის თარიღი შეგიძლია 07.2020 - present ასე დაწერო, რაც გულისხმობს, რომ პროცესი დღესაც გრძელდება და ასევე, სასაუბრო ენებს რა დონეზე ფლობ ესეც უკეთესი იქნება რომ მიუწერო. სერთიფიკატი რომ არ გქონდეს მაინც (თავად რა დონეზე თვლი რომ იცი მისაღები იქნება). 

რომ დაააფდეითებ მომწერე და კიდევ გადავხედავ, რომ მერე სიაში დავამატო ^^ <3

2021-02-17 09:43 UTC, theonomiMC commented
updated... ^-^

2021-11-19 17:11 UTC, closed without merging