Sandro Gachechiladze
bitcamp-ge/bitcamp-resume-review pull request #18
Opened 2020-09-08 12:51 UTC by Sandrodro

I will be adding other projects for the rest of the week

2020-10-06 17:37 UTC, otarza requested changes
@Sandrodro სანდრო გამარჯობა,

შენი რეზიუმე შინაარსობრივად კარგია, თუმცა სტილისტურად დალაგება სჭირდება, შენს ადგილას Latex - ში გაკეთებას ვცდიდი.

გაცილებით ლამაზეი და დალაგებული გამოგივა, აქ არის ინსტრუქცია: https://github.com/sdolidze/latex-resume

როცა გადაიყვან აქვე ატვირთე ახალი ვარიანტი და დამიკომენტარე რომ შევამოწმო.
:rocket:

2021-02-15 23:32 UTC, TGociridze commented
@Sandrodro გამარჯობა, შენი რეზიუმე სარეკომენდაციო სიაში დავამატე, თებერვლის თვის დასაქმების რაუნდის ფარგლებში.

2021-02-16 11:14 UTC, Sandrodro commented
@TGociridze  მადლობა^
დღეს ისე ცოტათი ხელს შევავლებ, კიდევ ორი პროექტი უნდა დავამატო

2021-02-16 19:57 UTC, TGociridze commented
კიბატონო, შემატყობინე როცა მზად გექნება და შევცვლი ფაილს ^^

2021-02-17 14:41 UTC, Sandrodro commented
@TGociridze 
აი, 20201/winter-ში დავამატე ახალი რეზიუმე ჩემს ბრენჩზე

2021-02-18 08:14 UTC, TGociridze commented
კიბატონო, სიაშიც ჩავასწორე
წარმატებები ^^

2021-11-19 17:11 UTC, closed without merging