Lasha Giorgi Intskirveli
bitcamp-ge/bitcamp-resume-review pull request #2
Opened 2020-09-06 16:55 UTC by 1ntsko

2020-09-21 13:27 UTC, sdolidze requested changes
ოთოს რჩევებს ვეთანხმები, მეც მომწონს, good job 🔥

2020-10-21 07:04 UTC, otarza approved these changes

2021-02-15 22:51 UTC, TGociridze commented
@1ntsko გამარჯობა, შენი რეზიუმე სარეკომენდაციო სიაში დავამატე თებერვლის თვის დასაქმების რაუნდის ფარგლებში.

2021-02-25 11:44 UTC, 1ntsko commented
@TGociridze გამარჯობა და ბოდიში დაგვიანებული პასუხისთვის. გთხოვ, თუ არის შესაძლებელი ამოიღო ჩემი რეზიუმე სარეკომენდაციო სიიდან. მადლობა.

2021-02-25 19:18 UTC, TGociridze commented
კიბატონო, არ არის პრობლემა

თუ მუშაობა დაიწყე და ამიტომ მთხოვე ამოღება, თუ შეგიძლია ამ კითხვებზე რომ მიპასუხო:

- ელ.ფოსტა
- ტელეფონი
- ბითქემფის დაწყებიდან რამდენ ხანში დაიწყე მუშაობა
- რომელ კომპანიაში მუშაობ
- რა პოზიციაზე მუშაობ და რა ტექნოლოგიებს იყენებ

მადლობა <3

2021-02-25 19:43 UTC, 1ntsko commented
- giorgilasha3@gmail.com

- 568701121

- ბითქემფის დაწყებიდან დაახლოებით 5 თვეში დავიწყე მუშაობა

- ვმუშაობ კომპანია Singular-ში

- ვარ სტაჟიორი. ტექნოლოგიებიდან ვიყენებ ჯერჯერობით მხოლოდ vanilla js-ს. სამომავლოდ იგეგმება angular-ის და typescript-ის გამოყენება

2021-02-25 19:54 UTC, TGociridze commented
ძალიან დიდი მადლობა და წარმატებები <3

2021-02-25 19:57 UTC, 1ntsko commented
მადლობა შენ.

On Thu, 25 Feb 2021, 23:54 TGociridze, <notifications@github.com> wrote:

> ძალიან დიდი მადლობა და წარმატებები <3
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcamp-ge/bitcamp-resume-review/pull/2#issuecomment-786160322>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APNEN7XRUBZLBLHYZ2OFP5LTA2TIFANCNFSM4Q4UMZGQ>
> .
>

2021-11-19 17:12 UTC, closed without merging